name: Build
on:
  push:
    branches: [ main ]
 
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
 
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'

      - name: Build Image
        run: ./gradlew bootBuildImage --imageName=junkmen0927/devopstest:${{github.run_number}}
 
      - name: Docker Login
        uses: docker/login-action@v1.8.0
        with:
          username: junkmen0927
          password: dckr_pat_kISXJOJ0HYl5_09aauIPSJunHEw
 
      - name: Push Image
        run: docker push junkmen0927/devopstest:${{github.run_number}}
