name: Build
on:
  push:
    branches: [ main ]
 
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
 
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
 
      - name: Build Image
        run: ./gradlew bootBuildImage --imageName=junkmen0927/devopsttest:${{github.run_number}}
 
      - name: Docker Login
        uses: docker/login-action@v1.8.0
        with:
          username: junkmen0927
          password: Cn19900927
 
      - name: Push Image
        run: docker push junkmen0927/devopsttest:${{github.run_number}}
